### ISSUE TITLE
Modyfying Already Implemented Code

### ISSUE THREAD

**Issue by jake32321** [TheOneWhoCodes/CS-412-Lab-7#1]
So I think the body of the source code exists in one of the labs we did.  Are you guys using that as a base?

**Comment by TheOneWhoCodes** [comment]
No, we are using Oracle's Java RMI tutorial code as our base. You can check it out here: http://docs.oracle.com/javase/7/docs/technotes/guides/rmi/hello/hello-world.html

**Comment by jake32321** [comment]
Coolio!
